/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Biao1: typeof import('./components/Board/biao1.vue')['default']
    Biao2: typeof import('./components/Board/biao2.vue')['default']
    Biao3: typeof import('./components/Board/biao3.vue')['default']
    Biao4: typeof import('./components/Board/biao4.vue')['default']
    Biao5: typeof import('./components/Board/biao5.vue')['default']
    Biao6: typeof import('./components/Board/biao6.vue')['default']
    Biao7: typeof import('./components/Board/biao7.vue')['default']
    DataBoard: typeof import('./components/dataBoard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GeRen: typeof import('./components/geRen.vue')['default']
    LineEcharts1: typeof import('./components/echarts/lineEcharts1.vue')['default']
    LineEcharts2: typeof import('./components/echarts/lineEcharts2.vue')['default']
    LineEchartsL: typeof import('./components/echarts/lineEchartsL.vue')['default']
    Other: typeof import('./components/echarts/other.vue')['default']
    PieEcharts1: typeof import('./components/echarts/pieEcharts1.vue')['default']
    PieEcharts2: typeof import('./components/echarts/pieEcharts2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
